# NumPy
Short for Numerical Python, NumPy is a foundational package for numerical computing in Python, ndarray is an efficient multidimensional array provinding fast array oriented operations

In [10]:
import numpy as np

In [8]:
a = np.arange(1000000)
l = list(range(1000000))

In [9]:
%timeit for i in range(1000): a2 = a * 2

KeyboardInterrupt: 

In [ ]:
%timeit for i in range(1000): l2 = l * 2

## Creating ndarrays

In [ ]:
data = [1,2,3,4,5]
a1 = np.array(data)
a1

In [ ]:
type(a1)

In [ ]:
data = [[1,2,3,4,5], [1,2,3,4,5]]
a1 = np.array(data)
a1

In [ ]:
data = [[1,2,3,4,5], [1,2,3,4,5]]
a1 = np.array(data, dtype = np.float64)
a1

In [ ]:
a1.shape

In [ ]:
a1.dtype

In [131]:
a1.ndim
a1  = np.arange(10)
print(a1.dtype)
a1

int32


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
a1 = a1.astype('float64')
print(a1.dtype)
a1

float64


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
data = [[[1,2,3,4,5], [1,2,3,4,5,]]]
a1 = np.array(data)
a1

In [ ]:
a1.ndim

In [ ]:
a1 = np.arange(10)
a1

In [ ]:
np.ones((3,3))

In [ ]:
np.zeros((3,3))

In [ ]:
np.full((5,5), fill_value = 5)

In [ ]:
np.full((5,5), 5)

In [ ]:
np.eye(5)

In [ ]:
np.empty((3,3))

In [ ]:
np.full((5,5), 7)

In [ ]:
np.empty((7,7))

## Data Types in numpy

In [ ]:
np.arange(5, dtype = np.int16)

In [ ]:
np.arange(5, dtype = np.int32).dtype

In [ ]:
np.arange(5, dtype = np.float32)

In [ ]:
np.arange(5, dtype = np.float64).dtype

## Arithmatic operations

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a1

In [ ]:
a1 + 2

In [ ]:
a1

In [ ]:
a1 + a1

In [ ]:
a1 * 2

In [ ]:
a1 // 2

In [ ]:
a1 ** 2

In [ ]:
6 / a1

In [ ]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [ ]:
a1 > a2

In [ ]:
a1 < a2

## Indexing and Slicing

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[0]

0

In [14]:
a[-1]

9

In [15]:
a[5]

5

In [16]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[::2]

array([0, 2, 4, 6, 8])

In [19]:
a2 = np.arange(11)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a2[:3] = 11

In [23]:
a2

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a2[:] = 22

In [26]:
a2

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [27]:
a1 = np.arange(10)
a2 = a1

In [28]:
a2[:3] = 11
a2

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9])

In [29]:
a1

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9])

In [30]:
a1 = np.arange(10)
a2 = a1[:5]

In [31]:
a2

array([0, 1, 2, 3, 4])

In [32]:
a2[:] = 11
a2

array([11, 11, 11, 11, 11])

In [33]:
a1

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [35]:
a1 = np.arange(10)
c1 = a1.copy()
c1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
c1[:5] = 11
c1

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reshaping and Transposing

In [38]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
a.shape

(16,)

In [43]:
a1 = a.reshape((16,1))

In [44]:
a1.shape

(16, 1)

In [45]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
a.reshape((8,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [48]:
a.reshape((5,4))

ValueError: cannot reshape array of size 16 into shape (5,4)

In [49]:
a1 = a.reshape((4,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
a1 = a1.T

In [54]:
np.dot(a1, a1.T)

array([[224, 248, 272, 296],
       [248, 276, 304, 332],
       [272, 304, 336, 368],
       [296, 332, 368, 404]])

## Functions For ndarrays

In [55]:
a = np.array([2,4,3,7,8,9,2,6,7,1])
a

array([2, 4, 3, 7, 8, 9, 2, 6, 7, 1])

In [56]:
a.sort()

In [57]:
a

array([1, 2, 2, 3, 4, 6, 7, 7, 8, 9])

In [60]:
s = np.square(a)
s

array([ 1,  4,  4,  9, 16, 36, 49, 49, 64, 81], dtype=int32)

In [62]:
np.sqrt(s)

array([1., 2., 2., 3., 4., 6., 7., 7., 8., 9.])

In [64]:
np.abs([-1,-2,-3,4])

array([1, 2, 3, 4])

In [65]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])
np.add(a1,a2)

array([ 6,  8, 10, 12, 14])

In [66]:
a1 + a2

array([ 6,  8, 10, 12, 14])

In [67]:
np.subtract(a2,a1)

array([4, 4, 4, 4, 4])

In [68]:
a2 - a1

array([4, 4, 4, 4, 4])

In [69]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7])
np.add(a1,a2)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [71]:
a1 = np.array([2,5,1,6,5,9])
a2 = np.array([4,3,7,8,2,4])
np.maximum(a1,a2)

array([4, 5, 7, 8, 5, 9])

In [72]:
np.minimum(a1,a2)

array([2, 3, 1, 6, 2, 4])

In [73]:
np.power(a2,a1)

array([    16,    243,      7, 262144,     32, 262144], dtype=int32)

In [74]:
np.greater(a1,a2)

array([False,  True, False, False,  True,  True])

In [75]:
np.less(a1,a2)

array([ True, False,  True,  True, False, False])

In [77]:
np.cbrt([8])

array([2.])

## Math and stats functions

In [76]:
a = np.array([2,3,4,2,8,7,4,9,3])
a.mean()

4.666666666666667

In [78]:
np.mean(a)

4.666666666666667

In [79]:
a.sum()

42

In [80]:
a.min()

2

In [81]:
a.max()

9

In [82]:
a.var()

6.222222222222222

In [83]:
a.std()

2.494438257849294

In [84]:
np.sqrt(6.2222)

2.4944338034912854

In [85]:
a.cumsum()

array([ 2,  5,  9, 11, 19, 26, 30, 39, 42], dtype=int32)

In [86]:
a.cumprod()

array([     2,      6,     24,     48,    384,   2688,  10752,  96768,
       290304], dtype=int32)

In [88]:
np.median(a)

4.0

In [89]:
a = np.arange(25)
a = a.reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
a.mean(axis = 1)

array([ 2.,  7., 12., 17., 22.])

In [91]:
a.mean(axis = 0)

array([10., 11., 12., 13., 14.])

In [92]:
a.dot(a.T)

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

In [93]:
from numpy.linalg import det, inv, eig

In [101]:
a = np.array([4,2,3,6,7,2,3,8,9]).reshape((3,3))

In [102]:
a

array([[4, 2, 3],
       [6, 7, 2],
       [3, 8, 9]])

In [103]:
det(a)

172.99999999999991

In [104]:
inv(a)

array([[ 0.2716763 ,  0.03468208, -0.0982659 ],
       [-0.27745665,  0.15606936,  0.05780347],
       [ 0.15606936, -0.15028902,  0.09248555]])

In [105]:
eig(a)

(array([14.66841007+0.j        ,  2.66579496+2.16508425j,
         2.66579496-2.16508425j]),
 array([[-0.31936903+0.j        ,  0.04421692-0.43432912j,
          0.04421692+0.43432912j],
        [-0.46520477+0.j        , -0.52778974+0.33760872j,
         -0.52778974-0.33760872j],
        [-0.8255834 +0.j        ,  0.64564806+0.j        ,
          0.64564806-0.j        ]]))

In [108]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
det(a)

0.0

In [113]:
np.random.randint(100)

4

In [121]:
np.random.randint(10)

8

In [118]:
np.random.rand(10)

array([0.65597276, 0.58363928, 0.73564137, 0.17533134, 0.56138362,
       0.85029455, 0.22742136, 0.9723215 , 0.34241339, 0.70889733])

In [126]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
def square(n):
    return n**2

In [128]:
list(map(square,a))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]